// Command preview serves the frontend with a stand-in for everything it talks
// to, so the page can be clicked through locally without an AWS account.
//
// It fakes three things:
//
//   - Cognito, enough for the two-step password + MFA login the page performs
//   - the API, i.e. /upload-url, /files and /download-url
//   - S3 itself, as an in-memory store behind the presigned URLs it hands out
//
// It is a development aid and nothing else. It accepts ANY username, password
// and MFA code, and it never checks the bearer token it is given. Do not deploy
// it, and do not take its behavior as a specification: lambda/handler.go is the
// real implementation, and where the two disagree, that one is right.
//
// The parts it does mirror faithfully are the ones the frontend depends on: the
// key format (a timestamp directory plus a filename), the filename allowlist,
// and the shape of every JSON response.
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"regexp"
	"slices"
	"sort"
	"strings"
	"sync"
	"time"
)

// storedFile is one object in the in-memory stand-in for S3.
type storedFile struct {
	data         []byte
	contentType  string
	lastModified time.Time
}

// store is the fake bucket. A mutex because uploads arrive concurrently — the
// page fires them off in parallel when you drop several files at once.
//
// signedFor records the content type each minted URL was issued for. A real
// presigned PUT is signed over the content type, and S3 rejects the upload if
// the header does not match; mirroring that here turns a mismatch into a
// visible failure locally instead of a surprise against the real bucket.
var (
	storeMu   sync.Mutex
	store     = map[string]storedFile{}
	signedFor = map[string]string{}
)

// sanitizeForLog strips the characters that would let a value containing a
// newline forge additional log lines. Everything logged here comes from a
// request path or the environment, so none of it is trusted.
func sanitizeForLog(s string) string {
	return strings.Map(func(r rune) rune {
		if r < 0x20 || r == 0x7f {
			return -1
		}
		return r
	}, s)
}

// Mirrors the allowlist in lambda/handler.go, so the preview rejects exactly
// what production rejects and the browser-side sanitizer can be seen working.
var filenamePattern = regexp.MustCompile(`^[A-Za-z0-9._ -]+$`)

var keyPattern = regexp.MustCompile(`^\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2}/[A-Za-z0-9._ -]+$`)

const expirySeconds = 300

func main() {
	addr := ":8080"
	if p := os.Getenv("PORT"); p != "" {
		addr = ":" + p
	}

	root := os.Getenv("FRONTEND_DIR")
	if root == "" {
		root = "./frontend"
	}

	mux := http.NewServeMux()

	// config.js is served rather than read from disk. The real one is generated
	// per deployment and gitignored; this hands the page preview settings and
	// doubles as a demonstration of the cognitoUrl override.
	mux.HandleFunc("/config.js", serveConfig)

	mux.HandleFunc("/mock-cognito/", handleCognito)

	mux.HandleFunc("/api/upload-url", handleUploadURL)
	mux.HandleFunc("/api/files", handleListFiles)
	mux.HandleFunc("/api/download-url", handleDownloadURL)

	// The stand-in for S3. Presigned URLs point here.
	mux.HandleFunc("/s3/", handleS3)

	// Everything else is the static site.
	mux.Handle("/", http.FileServer(http.Dir(root)))

	// The suppression below is for G706: gosec tracks taint through
	// sanitizeForLog without recognising it as a sanitizer. The control
	// characters that make log injection possible are stripped there.
	log.Printf("preview serving %s on http://localhost%s", sanitizeForLog(root), addr) //nolint:gosec // sanitized above
	log.Printf("log in with any username, password and 6-digit code")

	server := &http.Server{
		Addr:              addr,
		Handler:           mux,
		ReadHeaderTimeout: 10 * time.Second,
	}

	if err := server.ListenAndServe(); err != nil {
		log.Fatalf("server stopped: %v", err)
	}
}

func writeJSON(w http.ResponseWriter, status int, body any) {
	payload, err := json.Marshal(body)
	if err != nil {
		http.Error(w, `{"error":"could not encode response"}`, http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_, _ = w.Write(payload)
}

func writeError(w http.ResponseWriter, status int, msg string) {
	writeJSON(w, status, map[string]string{"error": msg})
}

func serveConfig(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "application/javascript")
	_, _ = fmt.Fprint(w, `// Generated by the preview server -- not the real config.js.
const CONFIG = {
  region: "us-east-1",
  clientId: "preview-client-id",
  apiBaseUrl: "/api",
  cognitoUrl: "/mock-cognito/",
};
`)
}

// handleCognito answers the two calls the page makes during login. The first
// always returns the MFA challenge; the second always succeeds.
func handleCognito(w http.ResponseWriter, r *http.Request) {
	action := r.Header.Get("X-Amz-Target")

	switch {
	case strings.HasSuffix(action, ".InitiateAuth"):
		writeJSON(w, 200, map[string]any{
			"ChallengeName": "SOFTWARE_TOKEN_MFA",
			"Session":       "preview-session",
		})

	case strings.HasSuffix(action, ".RespondToAuthChallenge"):
		writeJSON(w, 200, map[string]any{
			"AuthenticationResult": map[string]any{
				"IdToken": "preview-id-token",
			},
		})

	default:
		writeJSON(w, 400, map[string]string{"message": "unsupported action: " + action})
	}
}

func handleUploadURL(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		writeError(w, 404, "no such endpoint")
		return
	}

	var req struct {
		Filename    string `json:"filename"`
		ContentType string `json:"contentType"`
	}

	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, 400, "request body wasn't valid JSON")
		return
	}

	// The same checks lambda/handler.go makes, so the preview is honest about
	// what would be rejected in production.
	switch {
	case req.Filename == "":
		writeError(w, 400, "filename is required")
		return
	case len(req.Filename) > 255:
		writeError(w, 400, "filename is too long (max 255 characters)")
		return
	case strings.Contains(req.Filename, ".."), strings.HasPrefix(req.Filename, "/"):
		writeError(w, 400, "filename contains an illegal path")
		return
	case !filenamePattern.MatchString(req.Filename):
		writeError(w, 400, "filename has characters that aren't allowed")
		return
	}

	contentType := req.ContentType
	if contentType == "" {
		contentType = "application/octet-stream"
	}

	key := fmt.Sprintf("%s/%s", time.Now().Format("2006-01-02_15-04-05"), req.Filename)

	// Remember what this URL is good for, so the PUT can be checked against it
	// the way S3 checks a signature.
	storeMu.Lock()
	signedFor[key] = contentType
	storeMu.Unlock()

	writeJSON(w, 200, map[string]any{
		"uploadUrl": fmt.Sprintf("http://%s/s3/%s", r.Host, key),
		"key":       key,
		"expiresIn": expirySeconds,
	})
}

func handleListFiles(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		writeError(w, 404, "no such endpoint")
		return
	}

	storeMu.Lock()

	type entry struct {
		Key          string `json:"key"`
		Size         int64  `json:"size"`
		LastModified string `json:"lastModified"`
	}

	files := make([]entry, 0, len(store))
	for key, f := range store {
		files = append(files, entry{
			Key:          key,
			Size:         int64(len(f.data)),
			LastModified: f.lastModified.UTC().Format(time.RFC3339),
		})
	}

	storeMu.Unlock()

	// Real S3 returns keys in lexicographic order and the Lambda reverses that
	// for newest-first. A Go map has no order at all, so sort before reversing
	// to land in the same place.
	sort.Slice(files, func(i, j int) bool { return files[i].Key < files[j].Key })
	slices.Reverse(files)

	writeJSON(w, 200, map[string]any{"files": files})
}

func handleDownloadURL(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		writeError(w, 404, "no such endpoint")
		return
	}

	var req struct {
		Key string `json:"key"`
	}

	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, 400, "request body wasn't valid JSON")
		return
	}

	switch {
	case req.Key == "":
		writeError(w, 400, "key is required")
		return
	case strings.Contains(req.Key, ".."), strings.HasPrefix(req.Key, "/"):
		writeError(w, 400, "key contains an illegal path")
		return
	case !keyPattern.MatchString(req.Key):
		writeError(w, 400, "key is not in the expected form")
		return
	}

	writeJSON(w, 200, map[string]any{
		"downloadUrl": fmt.Sprintf("http://%s/s3/%s", r.Host, req.Key),
		"key":         req.Key,
		"expiresIn":   expirySeconds,
	})
}

// handleS3 is both ends of the presigned URL: PUT stores bytes, GET returns
// them. A real presigned URL carries a signature; this one carries nothing,
// which is one of several reasons this server is not deployable.
func handleS3(w http.ResponseWriter, r *http.Request) {
	key := strings.TrimPrefix(r.URL.Path, "/s3/")

	switch r.Method {
	case http.MethodPut:
		sent := r.Header.Get("Content-Type")

		storeMu.Lock()
		expected, minted := signedFor[key]
		storeMu.Unlock()

		// S3 signs a presigned PUT over the content type and rejects the upload
		// when the header disagrees. Reproducing that is the whole reason the
		// preview tracks what each URL was minted for: a frontend that sends a
		// different type than it asked for fails here rather than in production.
		if minted && sent != expected {
			log.Printf("rejected %s: signed for %q but sent %q", //nolint:gosec // values are sanitized
				sanitizeForLog(key), sanitizeForLog(expected), sanitizeForLog(sent))
			http.Error(w, "content type does not match the presigned URL", http.StatusForbidden)
			return
		}

		body := make([]byte, 0, r.ContentLength)
		buf := make([]byte, 32*1024)

		for {
			n, err := r.Body.Read(buf)
			body = append(body, buf[:n]...)
			if err != nil {
				break
			}
		}

		storeMu.Lock()
		store[key] = storedFile{
			data:         body,
			contentType:  sent,
			lastModified: time.Now(),
		}
		storeMu.Unlock()

		log.Printf("stored %s (%d bytes, %s)", sanitizeForLog(key), len(body), sanitizeForLog(sent)) //nolint:gosec // values are sanitized
		w.WriteHeader(http.StatusOK)

	case http.MethodGet:
		storeMu.Lock()
		f, ok := store[key]
		storeMu.Unlock()

		if !ok {
			http.NotFound(w, r)
			return
		}

		filename := key
		if i := strings.LastIndex(key, "/"); i >= 0 {
			filename = key[i+1:]
		}

		w.Header().Set("Content-Type", f.contentType)
		w.Header().Set("Content-Disposition", fmt.Sprintf("attachment; filename=%q", filename))
		_, _ = w.Write(f.data)

	default:
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
	}
}
