#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/../terraform"

REGION=$(terraform output -raw cognito_region 2>/dev/null || echo "us-east-1")
CLIENT_ID=$(terraform output -raw cognito_client_id)
API_URL=$(terraform output -raw api_base_url)

cd ..

{
  echo "// Auto-generated by scripts/gen-config.sh -- do not edit by hand."
  echo "const CONFIG = {"
  echo "  region: \"${REGION}\","
  echo "  clientId: \"${CLIENT_ID}\","
  echo "  apiBaseUrl: \"${API_URL}\","
  echo "};"
} > frontend/config.js

echo "Wrote frontend/config.js:"
cat frontend/config.js
